// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvyJGFcbkqHZ_cpmuKrAn1eDlG2tmW7d4',
    appId: '1:77801308486:web:cefc660ac9b43e337f6547',
    messagingSenderId: '77801308486',
    projectId: 'care-7b92d',
    authDomain: 'care-7b92d.firebaseapp.com',
    storageBucket: 'care-7b92d.appspot.com',
    measurementId: 'G-8Q3YX8Z183',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-q6004YfeXCTr-wNRNJTd8JtxVYLz80',
    appId: '1:77801308486:android:b2ca0862e6fe231a7f6547',
    messagingSenderId: '77801308486',
    projectId: 'care-7b92d',
    storageBucket: 'care-7b92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAATd0q7JbHsTQgK_7r0_5p8zeIvW1sm4w',
    appId: '1:77801308486:ios:21effa041c1b17377f6547',
    messagingSenderId: '77801308486',
    projectId: 'care-7b92d',
    storageBucket: 'care-7b92d.appspot.com',
    iosClientId: '77801308486-t2if0n5emeo21qkuba3u2ri1an1jh47h.apps.googleusercontent.com',
    iosBundleId: 'com.compwell.careapp.projectcareapp',
  );
}
